### ISSUE TITLE
arm64 graalvm-ce images contain x86 versions of GraalVM

### ISSUE THREAD

**Issue by lucascharlesmyers** [graalvm/container#37]
As the title says, the `linux/arm64` `graalvm-ce` images seem to actually contain x86 versions of GraalVM.

**Comment by quotidian-ennui** [comment]
`/community/Dockerfile.ol8-java11` appears to be correct on the master branch; so I'm guessing that it's something that was wrong with their actual build process

As a work-around I'm just copying the relevant bits out of their Dockerfile and patching my own Dockerfile.

It's not clever, but all the bootstrapping has already been done.

```
FROM ghcr.io/graalvm/graalvm-ce:ol8-java11-22
ARG TARGETPLATFORM
ARG GRAALVM_VERSION=22.0.0.2
ARG GRAALVM_PKG=https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-java11-GRAALVM_ARCH-$GRAALVM_VERSION.tar.gz
RUN rm -rf /opt/graalvm-ce-java11-$GRAALVM_VERSION \
    && set -eux \
    && if [ "$TARGETPLATFORM" == "linux/amd64" ]; then GRAALVM_PKG=${GRAALVM_PKG/GRAALVM_ARCH/linux-amd64}; fi \
    && if [ "$TARGETPLATFORM" == "linux/arm64" ]; then GRAALVM_PKG=${GRAALVM_PKG/GRAALVM_ARCH/linux-aarch64}; fi \
    && curl --fail --silent --location --retry 3 ${GRAALVM_PKG} | gunzip | tar x -C /opt/  \
    && java -version

... Rest of my Dockerfile.

```

` docker buildx build . --platform linux/arm64 -f graalvm/Dockerfile -t lewinc/interlok-base:graalvm-snapshot --load` works since as part of my Dockerfile I execute gradle...

**Comment by ezzarghili** [comment]
Thank you for your report, we will investigate this, as @quotidian-ennui mentioned, this is not an issue an issue in the dockerfiles but seems to be some bug on build process.

**Comment by ezzarghili** [comment]
This has been fixed, if you still face issues please feel free to re-open.

**Comment by ezzarghili** [comment]
This has been fixed for 22, @mlouriz please confirm backport to 21.3.1.

**Comment by quotidian-ennui** [comment]
I'm on a windows machine today. It is currently 2022-01-31 0943 GMT


```
$ docker pull --platform linux/arm64 ghcr.io/graalvm/graalvm-ce:ol8-java11-22
ol8-java11-22: Pulling from graalvm/graalvm-ce
...
Digest: sha256:96c2b3fa9128ad144f1fed1f5d1d6e77655d110e9052f9c01d785f50e04e3b0b
Status: Downloaded newer image for ghcr.io/graalvm/graalvm-ce:ol8-java11-22
ghcr.io/graalvm/graalvm-ce:ol8-java11-22
$ docker-bash ghcr.io/graalvm/graalvm-ce:ol8-java11-22
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
bash-4.4# java -version
openjdk version "11.0.14" 2022-01-18
OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 11.0.14+9-jvmci-22.0-b05)
OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 11.0.14+9-jvmci-22.0-b05, mixed mode)
bash-4.4# exit
```

- It's fixed for `ol8-java11-22` which _fixes my issue_ 


```
$ docker pull --platform linux/arm64 ghcr.io/graalvm/graalvm-ce:ol8-java11-21
ol8-java11-21: Pulling from graalvm/graalvm-ce
...
Digest: sha256:09e817ed9d5fa6eb55e5ccbc2540f9c5988613df9cb4a8547a7c2f7be0945689
Status: Downloaded newer image for ghcr.io/graalvm/graalvm-ce:ol8-java11-21
ghcr.io/graalvm/graalvm-ce:ol8-java11-21
$ docker-bash ghcr.io/graalvm/graalvm-ce:ol8-java11-21
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
bash-4.4# java -version
bash: /usr/bin/java: No such file or directory
bash-4.4#
```

- __It's not fixed for the tag `ol8-java11-21`__; I was already suspicious because the _last updated_ time for the 21.x graalvm containers all date from before this issue

**Comment by ezzarghili** [comment]
@quotidian-ennui Thank you for your feed back, we are aware of this, see my comment before yours.
> This has been fixed for 22, @mlouriz please confirm backport to 21.3.1.

**Comment by ezzarghili** [comment]
This has been fixed for 21, please feel free to re-open if you are still facing issues.
